# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  research = {
    pname = "research";
    version = "1.0.0";
    src = fetchurl {
      url = "https://un.ms/research/downloads/1.0.0/Research_1.0.0_amd64.deb";
      sha256 = "sha256-lRcK2JUKzYVf/OQVGAk0cLqmACMl+SUCCKiTvueuy6M=";
    };
  };
}
